# Generated by Django 5.2.4 on 2025-07-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
